# Generated by Django 5.1.1 on 2024-09-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
