# Generated by Django 5.1.1 on 2024-09-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_against'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='against',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='province',
            field=models.CharField(choices=[('Eastern Cape', 'Eastern Cape'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng'), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Limpopo', 'Limpopo'), ('Mpumalanga', 'Mpumalanga'), ('North West', 'North West'), ('Western Cape', 'Western Cape'), ('Northern Cape', 'Northern Cape,')], max_length=100),
        ),
    ]
