# Generated by Django 5.1.1 on 2024-11-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, choices=[('legal', 'Legal User'), ('normal', 'Normal user')], max_length=100),
        ),
    ]
